<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relaciones1" nsURI="http:///relaciones1.ecore" nsPrefix="relaciones1">
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thesintaxisAbstracta" lowerBound="1"
        eType="#//SintaxisAbstracta" containment="true" eOpposite="#//SintaxisAbstracta/theModelFactory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thesintaxisConcreta" lowerBound="1"
        eType="#//SintaxisConcreta" containment="true" eOpposite="#//SintaxisConcreta/theModelFactory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SintaxisAbstracta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theModelFactory" eType="#//ModelFactory"
        transient="true" eOpposite="#//ModelFactory/thesintaxisAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTabla" upperBound="-1"
        eType="ecore:EClass sintaxisabstracta.ecore#//Tabla" containment="true" eOpposite="sintaxisabstracta.ecore#//Tabla/thesintaxisAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SintaxisAbstracta" upperBound="-1"
        eType="#//SintaxisAbstracta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SintaxisConcreta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theModelFactory" eType="#//ModelFactory"
        transient="true" eOpposite="#//ModelFactory/thesintaxisConcreta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTabla" upperBound="-1"
        eType="ecore:EClass sintaxisabstracta.ecore#//Tabla" containment="true" eOpposite="sintaxisabstracta.ecore#//Tabla/thesintaxisConcreta"/>
  </eClassifiers>
</ecore:EPackage>
