<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sintaxisabstracta" nsURI="http:///sintaxisabstracta.ecore" nsPrefix="sintaxisabstracta">
  <eClassifiers xsi:type="ecore:EClass" name="Tabla">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theCampo" lowerBound="1"
        upperBound="-1" eType="#//Campo" containment="true" eOpposite="#//Campo/theTabla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thesintaxisAbstracta" eType="ecore:EClass relaciones.ecore#//SintaxisAbstracta"
        transient="true" eOpposite="relaciones.ecore#//SintaxisAbstracta/theTabla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thecardinalidad" lowerBound="1"
        eType="#//Cardinalidad" containment="true" eOpposite="#//Cardinalidad/thetabla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theRelaciones" lowerBound="1"
        upperBound="-1" eType="#//Relaciones" containment="true" eOpposite="#//Relaciones/theTabla"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thesintaxisConcreta" eType="ecore:EClass relaciones.ecore#//SintaxisConcreta"
        transient="true" eOpposite="relaciones.ecore#//SintaxisConcreta/theTabla"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Campo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etiqueta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTabla" eType="#//Tabla"
        transient="true" eOpposite="#//Tabla/theCampo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTipo_Dato" lowerBound="1"
        eType="#//Tipo_Dato" containment="true" eOpposite="#//Tipo_Dato/theCampo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cardinalidad">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thetabla" eType="#//Tabla"
        transient="true" eOpposite="#//Tabla/thecardinalidad"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theRelaciones" eType="#//Relaciones"
        transient="true" eOpposite="#//Relaciones/theCardinalidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tipo_Dato">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theCampo" eType="#//Campo"
        transient="true" eOpposite="#//Campo/theTipo_Dato"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Tipo_Dato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Numeric" eSuperTypes="#//Tipo_Dato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//Tipo_Dato"/>
  <eClassifiers xsi:type="ecore:EClass" name="Uno" eSuperTypes="#//Cardinalidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unomuchos" eSuperTypes="#//Cardinalidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cero" eSuperTypes="#//Cardinalidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ceromuchos" eSuperTypes="#//Cardinalidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Muchos" eSuperTypes="#//Cardinalidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cerouno" eSuperTypes="#//Cardinalidad"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relaciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tablarelacionada" eType="#//Tabla"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTabla" eType="#//Tabla"
        transient="true" eOpposite="#//Tabla/theRelaciones"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theCardinalidad" lowerBound="1"
        eType="#//Cardinalidad" containment="true" eOpposite="#//Cardinalidad/theRelaciones"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewClass"/>
</ecore:EPackage>
